import { Container, Row, Col, Stack } from "react-bootstrap";
import * as Icons from "react-bootstrap-icons";
import Author from "./Author";

export default function Footer() {
  return (
    <Container className={"m-auto p-auto py-5 mx-0"}>
      <Row>
        <Col className={"ps-0 m-auto p-auto text-secondary fw-light"}>
          <p>Intelligence (AI), Machine Learning (ML) created Poems.</p>
          <p>
            A portfolio website of poems generated by machine learning models
            managed by <Author />
          </p>
        </Col>
        <Col className={"fs-3 text-center m-auto p-auto pe-0"}>
          <div className={"m-auto text-center"}>
            <a
              className={"mx-2"}
              href={"https://www.linkedin.com/in/frankvillasenor/"}
            >
              <Icons.Linkedin />
            </a>

            <a className={"mx-2"} href={"http://www.theOpenSourceU.org"}>
              <Icons.Projector />
            </a>
          </div>
        </Col>
        <Col
          className={
            "m-auto p-auto pe-0 text-secondary position-relative bottom-0 end-0 text-end"
          }
        >
          2023-2024 &copy; Frank Villasenor
        </Col>
      </Row>
    </Container>
  );
}
