import { Container, Row, Col, Stack } from "react-bootstrap";
import * as Icons from "react-bootstrap-icons";
import Author from "./Author";
import { IconGitHub, IconLinkedIn, IconTheOpenSourceUorg } from "./Icons";
import CCLicense from "./CCLicense";

export default function Footer() {
  return (
    <Container className={"m-auto p-auto py-5 mx-0"}>
      <Row>
        <Col className={"ps-0 m-auto p-auto text-secondary fw-light"}>
          <p>
            Artificial Intelligence (AI) / Machine Learning (ML) created Poems.
          </p>
          <p>
            A portfolio website containing poems generated by machine learning
            models managed by <Author className={"link-secondary"} />
          </p>
        </Col>
        <Col className={"fs-3 text-center m-auto p-auto pe-0"}>
          <div className={"m-auto text-center"}>
            <IconLinkedIn className={"mx-2"} />
            <IconGitHub className={"mx-2"} />
            <IconTheOpenSourceUorg className={"mx-2"} />
          </div>
        </Col>
        <Col
          className={
            "m-auto p-auto pe-0 text-secondary small position-relative bottom-0 end-0 text-end"
          }
        >
          <div>
            Made with <Icons.HeartFill /> by Frank Villasenor
          </div>
          <div>
            Dedicated with <Icons.HeartPulseFill /> to my Wife, Alina
          </div>
          <div>2023-2024 &copy; Frank Villasenor</div>
          <div>
            <CCLicense />
          </div>
        </Col>
      </Row>
    </Container>
  );
}
