import { Container, Row, Col } from "react-bootstrap";
import Author from "./Author";

const space: string = " ";

function LandingBanner() {
  return (
    <Container>
      <Row>
        <Col>
          <h1>
            Artificial Intelligence
            <span className={"text-secondary"}>(AI)</span>, Machine Learning
            {space}
            <span className={"text-secondary"}>(ML)</span> based Poems.
          </h1>
          <p>
            A portfolio of poems generated by machine learning models trained by
            {space}
            <Author />
          </p>
        </Col>
        <Col>Vertical Image goes here</Col>
      </Row>
    </Container>
  );
}
export default LandingBanner;
