import { Container, Row, Col } from "react-bootstrap";
import Author from "./Author";
import Image from "next/image";
const space: string = " ";

function LandingBanner() {
  const logos = [
    "/logo_2023-12-04T18-59-05.png",
    "/logo_2023-12-04T19-11-38.png",
    "/logo_2023-12-04T19-14-19.png",
  ];

  return (
    <Container>
      <Row>
        <Col xl={8} lg={7} md={5}>
          <h1>
            Artificial Intelligence
            <span className={"text-secondary"}>(AI)</span>, Machine Learning
            {space}
            <span className={"text-secondary"}>(ML)</span> based Poems.
          </h1>
          <p>
            A portfolio website of poems generated by machine learning models
            trained by
            {space}
            <Author />
          </p>
        </Col>
        <Col xl={4} lg={5} md={7} className={"me-0 pe-0"}>
          <Image
            alt={"AI Poems by Frank Villasenor"}
            className={"shadow p-1 pe-0 rounded float-end rounded fluid"}
            src={
              logos.find(
                (logo, indx) =>
                  indx === Math.floor(Math.random() * logos.length),
              ) || logos[0]
            }
            width={400}
            height={400}
          />
        </Col>
      </Row>
    </Container>
  );
}
export default LandingBanner;
