import { Container, Row, Col } from "react-bootstrap";
import Author from "./Author";
import Image from "react-bootstrap/Image";

const space: string = " ";

function LandingBanner() {
  return (
    <Container>
      <Row>
        <Col className={"m-auto"}>
          <h1>
            Artificial Intelligence
            <span className={"text-secondary"}>(AI)</span>, Machine Learning
            {space}
            <span className={"text-secondary"}>(ML)</span> based Poems.
          </h1>
          <p>
            A portfolio website of poems generated by machine learning models
            trained by
            {space}
            <Author />
          </p>
        </Col>
        <Col className={"mx-auto me-0 pe-0"}>
          <Image
            className={"shadow p-1 pe-0 rounded float-end"}
            rounded
            fluid
            src={"http://placekitten.com/500/400"}
          />
        </Col>
      </Row>
    </Container>
  );
}
export default LandingBanner;
